### PR TITLE
Better logger design

### PR DESCRIPTION
**Pull request by kirs**
- don't rewrite ActionController `logger` method
- don't make new instance of logger each time it's being accessed

### CODE REVIEW

**Comment by kirs** [comment]
@divineforest rebased

**Comment by kirs** [comment]
@divineforest smth wrong with this code?

**Comment by divineforest** [comment]
The name is just the same as controller name, looks redundant. Memoization is ok :). BTW there is a typo in geteway

**Comment by kirs** [comment]
@divineforest fixed. Now the naming is a way better :)

**Pull request merged**
